#!/usr/bin/env bash
BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
export NCODE_CONFIG=$BASE_DIR
# echo $BASE_DIR
# if [ ! -e $BASE_DIR/.local/config/nvim/fnl ]
# then
#   mkdir -p $BASE_DIR/.local/config/nvim
#   ln -s $BASE_DIR/fnl $BASE_DIR/.local/config/nvim/fnl
# fi
nvim -u $BASE_DIR/init.lua "$@"
